<?php


$arrayOfCountries = array("Afghanistan","Albania","Algeria","American Samoa","Andorra","Angola","Anguilla","Antarctica","Antigua","Argentina",
		"Armenia","Aruba","Ascension Island","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus",
		"Belgium",
		"Belize",
		"Benin",
		"Bermuda",
		"Bhutan",
		"Bolivia",
		"Bosnia and Herzegovina",
		"Botswana",
		"Brazil",
		"British Virgin Island",
		"Brunei",
		"Bulgaria",
		"Burkina Faso",
		"Burma Myanmar",
		"Burundi",
		"Cambodia",
		"Cameroon",
		"Canada",
		"Cape Verde Island",
		"Cayman Islands",
		"Central African Rep",
		"Chad Republic",
		"Chile",
		"China",
		"Christmas Island",
		"Cocos Island",
		"Colombia",
		"Comoros",
		"Congo",
		"Cook Islands",
		"Costa Rica",
		"Croatia",
		"Cuba",
		"Cyprus",
		"Czech Republic",
		"Dem Rep of Congo",
		"Denmark",
		"Diego Garcia",
		"Djibouti",
		"Dominica",
		"Dominican Republic",
		"East Timor",
		"Ecuador",
		"Egypt",
		"El Salvador",
		"Equatorial Guinea",
		"Estonia",
		"Ethiopia",
		"Faroe Islands",
		"Falkland Islands",
		"Fiji Islands",
		"Finland",
		"France",
		"French Antilles",
		"French Guiana",
		"French Polynesia",
		"Gabon Republic",
		"Gambia",
		"Georgia",
		"Germany",
		"Ghana",
		"Gibraltar",
		"Greece",
		"Greenland",
		"Grenada",
		"Guadeloupe",
		"Guam",
		"Guatemala",
		"Guinea",
		"Guinea Bissau",
		"Guyana",
		"Haiti",
		"Honduras",
		"Hong Kong",
		"Hungary",
		"Iceland",
		"India",
		"Indonesia",
		"Iran",
		"Iraq",
		"Ireland",
		"Israel",
		"Italy",
		"Ivory Coast",
		"Jamaica",
		"Japan",
		"Jordan",
		"Kazakhstan",
		"Kenya",
		"Kiribati",
		"Korea North",
		"Korea South",
		"Kuwait",
		"Kyrgyzstan",
		"Laos",
		"Latvia",
		"Lebanon",
		"Lesotho",
		"Liberia",
		"Libya",
		"Liechtenstein",
		"Lithuania",
		"Luxembourg",
		"Macao",
		"Macedonia",
		"Madagascar",
		"Malawi",
		"Malaysia",
		"Maldives",
		"Mali Republic",
		"Malta",
		"Mariana Islands",
		"Marshall Island",
		"Mauritania",
		"Mauritius",
		"Mexico",
		"Micronesia",
		"Moldova",
		"Monaco",
		"Mongolia",
		"Montenegro",
		"Montserrat",
		"Morocco",
		"Mozambique",
		"Namibia",
		"Nauru",
		"Nepal",
		"Netherlands",
		"Netherlands Antilles",
		"New Caledonia",
		"New Zealand",
		"Nicaragua",
		"Niger Republic",
		"Nigeria",
		"Niue",
		"Norway",
		"Oman",
		"Pakistan",
		"Palau",
		"Palestine",
		"Panama",
		"Papua New Guinea",
		"Paraguay",
		"Peru",
		"Peru Lima",
		"Philippines",
		"Poland",
		"Portugal",
		"Puerto Rico",
		"Qatar",
		"Reunion Island",
		"Rodriguez Islands",
		"Romania",
		"Russia",
		"Rwanda",
		"Saint Helena",
		"Saint Kitts",
		"Saint Lucia",
		"Saint Vincent",
		"San Marino",
		"Sao Tome",
		"Saudi Arabia",
		"Senegal Republic",
		"Serbia",
		"Seychelles",
		"Sierra Leone",
		"Singapore",
		"Slovakia",
		"Slovenia",
		"Solomon Islands",
		"Somalia",
		"South Africa",
		"Spain",
		"Sri Lanka",
		"Sudan",
		"Suriname",
		"Swaziland",
		"Sweden",
		"Switzerland",
		"Syria",
		"Taiwan",
		"Tajikstan",
		"Tanzania",
		"Thailand",
		"Togo",
		"Tonga Islands",
		"Trinidad and Tobago",
		"Tunisia",
		"Turkey",
		"Turkmenistan",
		"Turks and Caicos",
		"Tuvalu",
		"Uganda",
		"Ukraine",
		"United Arab Emirates",
		"Uruguay",
		"US Virgin Islands",
		"USA",
		"Uzbekistan",
		"Vanuatu",
		"Vatican City",
		"Venezuela",
		"Vietnam",
		"Wallis and Futuna",
		"Western Samoa",
		"Yemen",
		"Zambia",
		"Zimbabwe");

?>